export const DEFAULT_POLICY_RULES: Array<{
  ruleKey: string;
  ruleValue: string;
  description: string;
}> = [
  { ruleKey: 'sandwich_leave_enabled', ruleValue: 'true', description: 'Count holidays between leave days' },
  { ruleKey: 'comp_off_expiry_days', ruleValue: '90', description: 'Days until comp-off expires' },
  { ruleKey: 'comp_off_sunday_delivery', ruleValue: 'full', description: 'full or half' },
  { ruleKey: 'comp_off_sunday_travel', ruleValue: 'half', description: 'full or half' },
  { ruleKey: 'comp_off_expiry_behaviour', ruleValue: 'lapse', description: 'lapse or auto-encash' },
  { ruleKey: 'casual_leave_annual', ruleValue: '12', description: 'Annual casual leave days' },
  { ruleKey: 'sick_leave_annual', ruleValue: '12', description: 'Annual sick leave days' },
  { ruleKey: 'earned_leave_annual', ruleValue: '15', description: 'Annual earned leave days' },
  { ruleKey: 'half_day_threshold_hours', ruleValue: '4', description: 'Hours below which half day applies' },
  { ruleKey: 'grace_minutes', ruleValue: '15', description: 'Late grace period' },
  { ruleKey: 'consecutive_late_alert', ruleValue: '3', description: 'Consecutive lates before alert' },
  { ruleKey: 'consecutive_late_penalty', ruleValue: '4', description: 'Consecutive lates before half-day deduction' },
  { ruleKey: 'late_penalty_days', ruleValue: '0.5', description: 'Days deducted on late penalty' },
  { ruleKey: 'monthly_late_threshold', ruleValue: '6', description: 'Monthly late count triggering deduction' },
  { ruleKey: 'personal_absence_free_minutes_monthly', ruleValue: '120', description: 'Free personal step-out minutes/month' },
  { ruleKey: 'personal_absence_deduction_threshold_minutes', ruleValue: '240', description: 'Minutes before half-day deduction' },
  { ruleKey: 'overtime_threshold_time', ruleValue: '18:30', description: 'Extra hours start after this time' },
  { ruleKey: 'days_divisor', ruleValue: '26', description: 'Working days divisor for daily salary' },
  { ruleKey: 'travel_day_allowance', ruleValue: '0', description: 'Allowance for outstation travel on working day' },
  { ruleKey: 'engagement_target_monthly', ruleValue: '400', description: 'Monthly paid students engaged target' },
  { ruleKey: 'incentive_enabled', ruleValue: 'false', description: 'Show projected incentive' },
  { ruleKey: 'attendance_submission_window', ruleValue: 'same_day', description: 'Attendance create window' },
  { ruleKey: 'delivery_report_submission_window', ruleValue: 'same_day', description: 'Delivery report window' },
  { ruleKey: 'sales_activity_submission_window', ruleValue: 'same_day', description: 'Sales interaction window' },
  { ruleKey: 'dormancy_threshold_days', ruleValue: '60', description: 'Days without qualifying activity before dead (CRM ageing)' },
  { ruleKey: 'sales_ageing_warning_days', ruleValue: '45', description: 'Warn before 60-day dead ageing' },
  { ruleKey: 'school_workshop_min_students', ruleValue: '150', description: 'School workshop commercial-risk threshold' },
  { ruleKey: 'workshop_online_min_per_student', ruleValue: '550', description: 'Online workshop red-alert ₹/student' },
  { ruleKey: 'workshop_offline_min_per_student', ruleValue: '700', description: 'Offline workshop red-alert ₹/student' },
  { ruleKey: 'iasc_price_per_registration', ruleValue: '2000', description: 'IASC fixed price per registration' },
  { ruleKey: 'nac_school_price', ruleValue: '300', description: 'NAC school price per participant' },
  { ruleKey: 'nac_direct_price', ruleValue: '500', description: 'NAC direct/retail price per participant' },
  { ruleKey: 'explorium_single_book', ruleValue: '499', description: 'Explorium single book price' },
  { ruleKey: 'explorium_three_pack', ruleValue: '999', description: 'Explorium three-book pack price' },
  { ruleKey: 'retail_ownership_days', ruleValue: '90', description: 'Retail ownership duration days' },
  { ruleKey: 'nac_ownership_threshold', ruleValue: '50000', description: 'NAC ownership duration threshold (₹)' },
  { ruleKey: 'staffing_students_per_educator', ruleValue: '60', description: 'Norm students per educator' },
  { ruleKey: 'personal_data_retention_months', ruleValue: '84', description: 'Retention for personal records' },
  { ruleKey: 'credit_weight_enabled', ruleValue: 'false', description: 'Credit attribution enabled when matrix set' },
  { ruleKey: 'credit_weight_primary_educator', ruleValue: '1', description: 'Credit weight' },
  { ruleKey: 'credit_weight_secondary_educator', ruleValue: '0.5', description: 'Credit weight' },
  { ruleKey: 'credit_weight_primary_support', ruleValue: '0.25', description: 'Credit weight' },
  { ruleKey: 'credit_weight_secondary_support', ruleValue: '0.25', description: 'Credit weight' },
  { ruleKey: 'credit_weight_trainee', ruleValue: '0', description: 'Credit weight' },
  { ruleKey: 'credit_weight_observer', ruleValue: '0', description: 'Credit weight' },
];
